# Site settings
title: Hi, I'm Alexandre.
description: Alexandre Rodrigues' professional portfolio
# baseurl: "" 
url: "https://ratinhopets.github.io"

# User settings
username: Alexandre Rodrigues
user_title: 
user_job_title: Actuarial Analyst & Data Scientist
email: your.email [at] domain.com # Coloque seu email real aqui
# twitter_username: 
github_username: Ratinhopets

exclude: ['package.json', 'src' , 'node_modules']
